### ISSUE TITLE
report starting error.

### ISSUE THREAD

**Issue by zhanjiechen** [NKU-MobFly-Robotics/p3dx#1]
Hi, 
I am working on this project.
My operating system is ubuntu20.04, with ROS Noetic. 

When I run the gazebo simulation, the robot can be dsiplay normally. But there is an error:

```
[ERROR] [1745176381.141662686, 0.292000000]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/right_hub_joint 
[ERROR] [1745176381.142156152, 0.292000000]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/left_hub_joint
```

Then I added the pid gain params in the control.yaml:
```
gazebo_ros_control:
  pid_gains:
    left_hub_joint:
      p: 30.0
      i: 0.0
      d: 0.5
    right_hub_joint:
      p: 30.0
      i: 0.0
      d: 0.5
```

The error disappeared, but the robot model is break. It lost a wheel and under the ground in gazebo.
I am looking forward any help. Thank you.
